### ISSUE TITLE
I have no idea how to add code.

### ISSUE THREAD

**Issue by JamesBacon** [alli2191/ChatBot#5]
So here is a .rules command.
`
if (command === "rules") {
    const embed = new Discord.RichEmbed()
    .setColor('#27ae60')
    .addField("Rules!", "Rule #1: Don't make fun of God or Jesus! \n" +
    "Rule #2: Respect my wife!", false)
    msg.channel.send({embed})
  }
`

**Comment by alli2191** [comment]
Thanks, added
